### PR TITLE
no program has beeen changed

### PR DESCRIPTION
**Pull request by yharuhi39**
but operator ~ have to be used between [BLANK]. so I inserted [BLANK].

### CODE REVIEW

**Comment by kyllingstad** [comment]
Why? Is this some recent change in DMD that I'm not aware of?

**Comment by yharuhi39** [comment]
Ah... you may think "no program has been changed." "but-operator..."?
If you think so, that is misunderstand. "no program ... but, operator ...." is what I want to say.
otherwise Digital Mars are recommended [BLANK] between expressions and operators.

**Comment by kyllingstad** [comment]
> Digital Mars are recommended [BLANK] between expressions and operators.

Where did you read this recommendation?

This seems to be a style issue to me, unless you can point me to some DMD change that *requires* the use of blank spaces around concatenation operators.

**Comment by yharuhi39** [comment]
http://www.digitalmars.com/d/1.0/dstyle.html

This site they says
> Operators are separated by single spaces from their operands.

**Comment by kyllingstad** [comment]
The page you refer to is a *style guide* for D 1.0, and therefore not a requirement. For the most part, SciD adheres to the [newer D/Phobos style guide on dlang.org](http://dlang.org/dstyle.html), but again, this is just a guide, and there may be differences in style.

**Pull request closed without merging**
