### PR TITLE
update to DMD 2.068.0

### PR DESCRIPTION
**Pull request by 9il**

### CODE REVIEW

**Comment by 9il** [comment]
I hope to have a dub release with this patch ASAP.

**Comment by 9il** [comment]
Thanks!

**Comment by kyllingstad** [comment]
Since you asked for a new release: How does this affect client code?

I'm asking because the only change was in a unittest, and library unittests should normally not be compiled into client code.

**Comment by 9il** [comment]
Hmm... it is compiled into my code, see https://travis-ci.org/9il/atmosphere/jobs/75063217. How can I test my library without testing SciD?

**Comment by kyllingstad** [comment]
Ok, this seems like a Dub thing. Apparently it runs tests for dependencies as well, or it compiles the unittests into your code, I don't know which.

My point was that if you compile a library separately, and then use it in your build like this:

    dmd -unittest -I/path/to/imports -L-L/path/to/libs -L-lmylib mycode.d

Then the unittests for "mylib" will not be included in the "mycode" executable.

But anyway, we're all using Dub, so I just tagged a new version (v0.2.1).

**Pull request merged**
